name:               "Uta BÃ¼chler"
description:        "Ph.D. student in Computer Vision"

url:                ""
author:             "utabuechler"
email:              "utabuechler@web.de"
twitter:            "uta0590"
#email:              "utabuechler@web.de"
github:             "utabuechler"
#pinterest:          "jhondoe"
linkedin:           "jhondoe"
#facebook:           "jhondoe"

disqus_shortname:   "utabuechler"

background:         "/papers.co-vd21-black-sea-texture-40-wallpaper.jpg"
#"http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown
    
nav:
  - name:           "Home"
    href:           "/"
  - name:           "About Me"
    href:           "/aboutme"
  - name:           "Career"
    href:           "/career"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Contact"
    href:           "/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

highlighter: rouge
